#!/usr/bin/env bash
# Configure Nginx to add a custom header X-Served-By with the hostname
apt-get update
apt-get install -y nginx
sed -i 's/server_name _;/server_name _;\n\tadd_header X-Served-By $hostname;/' /etc/nginx/sites-available/default
service nginx restart
