#!/usr/bin/env bash
# Install and configure HAProxy for roundrobin load balancing
apt-get update
apt-get install -y haproxy
# Configure the backend web servers (using IPs from your server list)
echo "
frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 3.95.132.116:80 check
    server web-02 34.238.119.129:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable HAProxy and restart the service
sudo sed -i 's/^ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo service haproxy restart
