#!/usr/bin/env bash
# Fixes Nginx binding issue to listen on all active IPv4 IPs on port 80
kill -9 $(lsof -t -i:80)
sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:80;/' /etc/nginx/sites-available/default
service nginx restart
