#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.
apt-get update
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.html
sed -i 's/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/' /etc/nginx/sites-available/default
service nginx restart
