#!/usr/bin/env bash
# Configure Nginx default 404 error page
apt-get update
apt-get install -y nginx
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i 's/server_name _;/server_name _;\n\terror_page 404 \/404.html;/' /etc/nginx/sites-available/default
service nginx restart
